# Generated by Django 5.0.6 on 2024-07-16 18:04

import app_sgc.models
import datetime
import django.db.models.deletion
import stdimage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=app_sgc.models.get_file_path, variations={}, verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='MotivoChamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=50, verbose_name='Motivo Chamado')),
            ],
            options={
                'verbose_name': 'Motivo Chamado',
                'verbose_name_plural': 'Motivos Chamado',
            },
        ),
        migrations.CreateModel(
            name='NomeDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NomeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NomeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('protocolo', models.CharField(max_length=50, unique=True, verbose_name='Protocolo')),
                ('assunto_chamado', models.TextField(max_length=500, verbose_name='Assunto')),
                ('relato_chamado', models.TextField(max_length=500, verbose_name='Relato Chamado')),
                ('data_hora_chamado', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data e Hora do Chamado')),
                ('relato_suporte', models.TextField(max_length=500, verbose_name='Relato suporte')),
                ('data_hora_finalizado', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data e Hora de Finalização')),
                ('envia_avisos', models.EmailField(max_length=500, verbose_name='Email')),
                ('prazo', models.DateTimeField(blank=True, null=True, verbose_name='Prazo')),
                ('local_suporte', models.CharField(choices=[('Plenario', 'Plenario'), ('Departamento de Recursos Humanos', 'Departamento de Recursos Humanos'), ('Departamento de Contabilidade', 'Departamento de Contabilidade'), ('Departamento Financeiro', 'Departamento financeiro')], max_length=50)),
                ('status_chamado', models.CharField(choices=[('Recebida', 'Recebida'), ('Analise', 'Analise'), ('Finalizado', 'Finalizado')], default='Recebida', max_length=50)),
                ('usuario_criacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chamados_criados', to=settings.AUTH_USER_MODEL)),
                ('imagem_chamado', models.ManyToManyField(blank=True, to='app_sgc.imagemchamado')),
                ('motivo_chamado', models.ManyToManyField(to='app_sgc.motivochamado', verbose_name='Motivo do Chamado')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('nome_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sgc.nomedepartamento')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('nome_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sgc.nomeprofile')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criacao')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('nome_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sgc.nomeusuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
